apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent01
spec:
  capacity:
    storage: 1Gi
  accessModes:
  -ReadWriteOnce
  nfs:
    path: /home/data
    server: 192.168.1.104
  persistentVolumeReclaimPolicy: Recycle
